### ISSUE TITLE
Creating custom markers

### ISSUE THREAD

**Issue by lassemt** [webglearth/webglearth2#54]
Hey!

Is there a way to create custom dynamic markers with webGL Earth?

**Comment by klokan** [comment]
http://examples.webglearth.com/#markers

You can pass additional parameters when creating a marker to specify a custom image (and its width and height). For example: `app.initMarker(51.507222, -0.1275, url, width, height)`.

**Comment by lassemt** [comment]
I tried and got error in console: Uncaught TypeError: c.show is not a function in api.js on line 122.

My marker code is: 
`marker = TravelingTheGoodVibes.map.initMarker( position[0], position[1], "http://www.travelingthegoodvibes.dev/content/uploads/2014/08/test_logo.png", 75, 111);`

**Comment by petrsloup** [comment]
Although the above mentioned way should work as described, the alternative is to use `WE.marker`.
See update example: http://examples.webglearth.com/#markers

You can also use completely custom DOM instead of image.
For example https://github.com/cultureglobe/cultureglobe/blob/master/src/main.js#L413 uses this to create custom elements.

**Comment by williamdarkocode** [comment]
@petrsloup Is there a Javascript implementation example of the custom DOM method as you mentioned above?

**Comment by williamdarkocode** [comment]
Any comments on whether one can create custom DOM markes will be greatly appreciated
