### ISSUE TITLE
Is this project in progress?

### ISSUE THREAD

**Issue by echen1227** [webglearth/webglearth2#67]
Hi, I'm playing around with various map and earth library on browser
This project looks cool and it's not so complicate as cesiumjs

But it's API seems not completed, as there are a lot API in leafletjs I can't use here 
And the code isn't update frequently
So I'm just wondering is this project under a development plan?
Will the complete js API be released soon?

Thanks!

**Comment by klokan** [comment]
The project is actively maintained. It is an open-source project - if you need new functionality, feel free to improve the code or patch it. You can provide a pull request, we review the code and merge it to master.

There is no fixed roadmap. New release happens if new features are added or bugs fixed. We have developed what our clients wanted and released this code for free to community and we maintain the project to ensure it runs in new browsers and reported critical bugs are fixed. Others can reuse the existing code in their projects for free.

In case you need new specific features which you have trouble to develop yourself, we can agree on a contracted development - otherwise feel free to use the code which is here...

**Comment by echen1227** [comment]
Got it
Thanks for the reply!
